include colors.conf

# Font customization:
font_family Hurmit Nerd Font Mono
font_size 10

# Cursor:
cursor #E0A84B
cursor_shape block
shell_integration no-cursor

cursor_trail 1

# Colors:
background_opacity 0.8

# padding:
window_padding_width 3

listen_on unix:/tmp/kitty-{kitty_pid}
allow_remote_control yes
