[config]
reload_apps = true

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty.conf'
output_path = '~/.config/kitty/colors.conf'
post_hook = 'kitty @ set-colors -a ~/.config/kitty/colors.conf'

[templates.hyprland-borders]
input_path = '~/.config/matugen/templates/hyprland.conf'
output_path = '~/.config/hypr/colors.lua'

[templates.waybar]
input_path = "~/.config/matugen/templates/waybar.conf"
output_path = "~/.config/waybar/colors.css"
