[config]
reload_apps = true

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty.conf'
output_path = '~/.config/kitty/colors.conf'
post_hook = 'kitty @ set-colors -a ~/.config/kitty/colors.conf'

[templates.hyprland-borders]
input_path = '~/.config/matugen/templates/hyprland.conf'
output_path = '~/.config/hypr/colors.lua'

[templates.waybar]
input_path = "~/.config/matugen/templates/waybar.conf"
output_path = "~/.config/waybar/colors.css"

[templates.omp]
input_path  = '~/.config/matugen/templates/oh-my-posh.json'
output_path = '~/.config/oh-my-posh/themes/matugen.json'
post_hook   = 'pkill -SIGUSR1 $(pgrep -x zsh || pgrep -x bash)'
